source 'https://rubygems.org'

gem 'nokogiri', '~> 1.15', '>= 1.15.4'
gem 'curb', '~> 1.0', '>= 1.0.5'
gem 'addressable', '~> 2.8', '>= 2.8.6'
gem 'syntax_tree', '~> 6.2'
gem 'redcarpet', '~> 3.6'
gem 'kramdown', '~> 2.4.0'
gem 'kramdown-asciidoc', '~> 2.1.0'