= Scripts for cohost

Require Ruby and link:https://weasyprint.org[WeasyPrint] installed on your machine.

Use the version specified in `.ruby-version` and install the gem specified in `Gemfile`.

Scripts :

. `01_download_for_account.rb`: run with `01_download_for_account.rb ACCOUNT`, downloads all posts for an account `ACCOUNT` by page, and put them in `data/ACCOUNT/pages` directory. If you stop and restart it it will resume its work, delete the directory to restart it from scratch.
. `02_json_for_account.rb`: run with `02_json_for_account.rb ACCOUNT`, processed all pages in the `data/ACCOUNT/pages` directory and extract their JSON data content in the `data/ACCOUNT/json` directory, one JSON file per page and one main file called `main.json`.
. `03_ebook_for_account.rb.rb`: run with `03_ebook_for_account.rb ACCOUNT TAG`, read the JSON file from `data/ACCOUNT/json/main.json` file, filter all post with the specific `TAG`, transform their content in asciidoctor format, and put each of them in a separate file in the `data/ACCOUNT/asciidoctor/TAG` directory, and generate a main asciidoctor file as `data/ACCOUNT/asciidoctor/TAG/main.adoc` that contains links to them. The script tries to handle inter-posts links, put is very rough in extracting the contents (for example for quote post it doesn't retrieve the original content).
. `04_tags_for_account.rb`: run with `04_tags_for_account.rb ACCOUNT`, read the JSON file from `data/ACCOUNT/json/main.json` file and generate a file containing the list of posts for each tag sorted alphabeticaly in 
`data/ACCOUNT/tags.txt`

## Generate ebook

When you generated the asciidoctor file, you can use theses commands to generate an ebook, from the `data/ACCOUNT/asciidoctor/TAG` directory.

You can first edit the adoc file to add metadata like your name or a cover page, see the asciidoctor documentation or link:https://raw.githubusercontent.com/archiloque/blog/master/publies/microfictions-2023/all-pdf.asciidoc[here] for an example.

Create an EPUB:

[source,terminal]
----
asciidoctor-epub3 main.adoc
----

Create a PDF (store your custom CSS in `styles.css`, see link:https://github.com/archiloque/blog/blob/master/publies/microfictions-2023/styles.css[here] for an example):

[source,terminal]
----
asciidoctor -a stylesheet=styles.css main.adoc
weasyprint main.html main.pdf
----